- shell:
    - - git submodule update --init --recursive
      - Installing submodules
- defaults:
    link:
      relink: yes
- create:
    - ~/.bin
- link:
    ~/.bash_aliases: bash_aliases
    ~/.bash_logout: bash_logout
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.bin/copyfile: scripts/copyfile
    ~/.blerc: blerc
