#!/usr/bin/bash
function copyfile() {
	if [[ "$#" == 0 ]]; then
		local TEMP
		TEMP="$(mktemp)"
		cat >"$TEMP" || (rm -- "$TEMP"; return 1)
		local STAT
		STAT="$(stat -c '%s' -- "$TEMP")"
		if [[ "$STAT" == 0 ]] || [[ "$STAT" == "" ]]; then return 1; fi
		echo "File: $TEMP" >&2
		copyfile "$TEMP"
		return "$?"
	fi
	if [[ "$#" != 1 ]]; then
		echo "Usage: copy <file>"
		return 1
	fi
	filename="$1"
	if [[ ! -f "$1" ]]; then
		if [[ "$1" == "http://"* || "$1" == "https://"* ]]; then
			echo "Downloading file..." >&2
			filename="/tmp/$(base64 -w0 <<<"$1" | sed 's|/|_|g')"
			if [[ ! -f "$filename" ]]; then
				curl -sL -- "$1" >"$filename"
			fi
		else
			printf '"%s" is not a file\n' "$1"
			return 1
		fi
	fi
	local MIME
	MIME="$(file -Lb --mime-type -- "$filename")"
	echo "Mime type: $MIME" >&2
	wl-copy --type "$MIME" <"$filename"
}
